services:
  mongo:
    image: mongo:6
    container_name: mongo
    command: ["--replSet", "rs0"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-init:
    image: mongo:6
    container_name: mongo-init
    depends_on:
      - mongo
    restart: "no"
    entrypoint: >
      bash -c "
      sleep 5;
      mongosh --host mongo:27017 --eval '
        rs.initiate({
          _id: \"rs0\",
          members: [{ _id: 0, host: \"mongo:27017\" }]
        })
      ';
      "

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    container_name: auth
    env_file:
      - apps/auth/.env
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - mongo-init

  event:
    build:
      context: .
      dockerfile: apps/event/Dockerfile
    container_name: event
    env_file:
      - apps/event/.env
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - mongo-init

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    container_name: gateway
    env_file:
      - apps/gateway/.env
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - event

volumes:
  mongo-data:
